name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Vérifier le code source
      - name: Checkout the code
        uses: actions/checkout@v2

      # Étape 2: Configurer l'agent SSH pour utiliser la clé privée
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Assurez-vous d'utiliser le nom du secret correct

      # Étape 4: Déployer sur EC2 test endending of project 
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no prasolonjatovo@13.60.95.56 \
            "cd /home/prasolonjatovo/devOpslab/devOps_lab && git pull origin main && docker-compose down && docker-compose up -d && sudo systemctl restart nginx"
