name: Deploy to EC2

on:
  push:
    branches:
      - main  # ou la branche que tu veux utiliser pour le déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1: Vérifier le code source
    - name: Checkout the code
      uses: actions/checkout@v2

    # Étape 2: Configurer SSH pour se connecter à EC2
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    # Étape 3: Se connecter à EC2 et déployer
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/github-actions-ec2 ubuntu@<13.60.95.56> << 'EOF'
          cd /path/to/your/app
          git pull origin main  # Récupérer la dernière version du code
          docker-compose down  # Arrêter les containers existants
          docker-compose up -d  # Lancer les nouveaux containers
          # Redémarrer les services Nginx ou autres services nécessaires
          sudo systemctl restart nginx
        EOF
