name: Deploy to EC2

on:
  push:
    branches:
      - main  # ou la branche que tu veux utiliser pour le déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1: Vérifier le code source
    - name: Checkout the code
      uses: actions/checkout@v2

    # Étape 2: Configurer SSH pour se connecter à EC2
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Étape 3: Se connecter à EC2 et déployer
    - name: Deploy to EC2
      run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github-actions-ec2 prasolonjatovo@<13.60.95.56> "cd /devOpslab && git pull origin main && docker-compose down && docker-compose up -d && sudo systemctl restart nginx"